[project]
name = "maverick"
version = "0.1.0"
description = "Dive into Deep Learning study exercises using PyTorch"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "d2l==1.0.3",
    "nvidia-cublas-cu11==11.10.3.66; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-cuda-cupti-cu11==11.7.101; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-cuda-nvrtc-cu11==11.7.99; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-cuda-runtime-cu11==11.7.99; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-cudnn-cu11==8.5.0.96; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-cufft-cu11==10.9.0.58; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-curand-cu11==10.2.10.91; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-cusolver-cu11==11.4.0.1; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-cusparse-cu11==11.7.4.91; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-nccl-cu11==2.14.3; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "nvidia-nvtx-cu11==11.7.91; sys_platform == 'linux' and platform_machine == 'x86_64'",
    "torch==2.0.0",
    "torchvision==0.15.1",
    "triton==2.0.0; sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv]
package = false
